import { supabaseAdmin as supabase } from '../../../config/supabase.config.js';

/**
 * Creates pending tasks for clusters that don't have one yet.
 * @param {Array<Object>} prioritizedClusters - Clusters with priorities from mcdaPrioritizer
 * @returns {Array} Array of cleanup_tasks ready to be assigned
 */
export async function mapClustersToTasks(prioritizedClusters) {
  const createdTasks = [];

  for (const cluster of prioritizedClusters) {
    // 1. Check if cluster already has a cleanup_task
    const { data: existingTasks } = await supabase
      .from('cleanup_tasks')
      .select('id')
      .eq('cluster_id', cluster.id);
      
    if (existingTasks && existingTasks.length > 0) {
      continue; // Skip if already has a task
    }

    // 2. Fetch full cluster details to get issue_type and location
    const { data: clusterData } = await supabase
      .from('clusters')
      .select('id, issue_type, center, status, reports(id, cleanup_task_id)')
      .eq('id', cluster.id)
      .single();

    if (!clusterData || clusterData.status !== 'unresolved') continue;

    const reports = clusterData.reports || [];
    
    // Check if reports are already assigned to a custom task
    if (reports.some(r => r.cleanup_task_id !== null)) {
      continue; 
    }

    // 3. Create the pending cleanup_task
    const safeIssueType = clusterData.issue_type || 'general';
    const issueTypeDisplay = safeIssueType.charAt(0).toUpperCase() + safeIssueType.slice(1);
    const title = `${issueTypeDisplay} Cleanup - Cluster ${cluster.id.substring(0, 8)}`;
    const description = `Automated task generated by optimization run for a ${safeIssueType} cluster with ${reports.length} report(s).`;

    const { data: newTask, error } = await supabase
      .from('cleanup_tasks')
      .insert({
        cluster_id: cluster.id,
        title,
        description,
        status: 'pending',
        priority: cluster.priority,
        priority_score: cluster.priority_score,
        assigned_crew_ids: null, // Proposal only
        created_by: null // System generated
      })
      .select()
      .single();

    if (error || !newTask) {
      console.error('Failed to create task for cluster:', cluster.id, error);
      continue;
    }

    // 4. Update reports to link to this task
    if (reports.length > 0) {
      await supabase
        .from('reports')
        .update({ cleanup_task_id: newTask.id })
        .in('id', reports.map(r => r.id));
    }

    createdTasks.push(newTask);
  }

  return createdTasks;
}
